version: '3'

services:
  jenkins-master:
    image: jsdidierlaurent/jenkins-with-plugins
    ports:
      - 8080:8080
    volumes:
      - jenkins-master-home:/var/jenkins_home
    deploy:
      placement:
        constraints:
          - node.hostname == moby

volumes:
  jenkins-master-home:
    driver: local