version: '3'

services:
  jenkins-master:
    image: jsdidierlaurent/rpi-jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins-master-home:/var/jenkins_home
    deploy:
      placement:
        constraints:
          - node.hostname == vi.rpi.lan

volumes:
  jenkins-master-home:
    driver: local