version: '3'

networks:
  jenkins_swarm:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/16

services:
  jenkins-master:
    image: jsdidierlaurent/jenkins
    environment:
      - JAVA_OPTS=-Xmx2048m -XX:MaxPermSize=512m -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true
    ports:
      - 50000:50000
    networks:
      - jenkins_swarm
    volumes:
      - jenkins-master-home:/var/jenkins_home
    deploy:
      placement:
        constraints: [node.role == manager]
  
  jenkins-nginx:
    image: jsdidierlaurent/jenkins-nginx
    ports:
      - "80:80"
    networks:
      - jenkins_swarm 

  jenkins-slave:
    image: jsdidierlaurent/jenkins-regular-slave-maven
    command: 
      -username slave
      -password slave
      -executors 1
    environment:
      - "JENKINS_PORT_8080_TCP_ADDR=jenkins-master"
      - "JENKINS_PORT_8080_TCP_PORT=8080"
    networks:
      - jenkins_swarm
    volumes:
      - jenkins-slave-cache:/home/jenkins/.jenkins
      - jenkins-slave-m2:/home/jenkins/.m2
    deploy:
      mode: replicated
      replicas: 3

volumes:
  jenkins-master-home:
    driver: local
  jenkins-slave-cache:
    driver: local
  jenkins-slave-m2:
    driver: local