version: '3'

services:
  jenkins-master:
    image: jsdidierlaurent/jenkins
    environment:
      - JAVA_OPTS=-Xmx2048m -XX:MaxPermSize=512m -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-master-home:/var/jenkins_home
    deploy:
      placement:
        constraints: [node.role == manager]

  jenkins-slave:
    image: jsdidierlaurent/jenkins-regular-slave-maven
    command: 
      -master http://192.168.113.152:8080
      -username slave
      -password slave
      -executors 1
    volumes:
      - jenkins-slave-cache:$HOME/.jenkins
      - jenkins-slave-m2:$HOME/jenkins/.m2
    deploy:
      mode: replicated
      replicas: 3

volumes:
  jenkins-master-home:
    driver: local
  jenkins-slave-cache:
    driver: local
  jenkins-slave-m2:
    driver: local