version: '3'

services:
  jenkins-master:
    build: .
    image: jsdidierlaurent/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-master-home:/var/jenkins_home

volumes:
  jenkins-master-home:
    driver: local